type Product {
  id: ID
  title: String!
  price: Int!
  quantity: Int
}

type Query {
  products: [Product!]
  product(id: ID!): Product
}

input ProductInput {
  title: String!
  price: Int!
  quantity: Int
}

type Mutation {
  createProduct(data: ProductInput): Product
}
